/**
 * Time View Component
 * Story 6-2: CPM visualization with Gantt chart and timeline
 * Displays project schedule from agent pipeline output
 */

import { useState, useEffect, useMemo, useCallback, useRef } from 'react';
import { getCPM, saveCPM, calculateCriticalPath } from '../../services/cpmService';
import type { CPM, CPMTask } from '../../types/cpm';

interface TimeViewProps {
  projectId: string;
  userId?: string; // For saving changes
}

type ViewMode = 'gantt' | 'network' | 'list';

/**
 * Node position for network diagram layout
 */
interface NodePosition {
  x: number;
  y: number;
  width: number;
  height: number;
}

/**
 * Sample CPM data for when no real data exists
 * This simulates what the agent pipeline would produce
 */
const SAMPLE_CPM: CPM = {
  id: 'sample-cpm',
  projectId: 'sample',
  tasks: [
    { id: 't1', name: 'Site Preparation', duration: 2, dependencies: [], category: 'prep' },
    { id: 't2', name: 'Demolition', duration: 3, dependencies: ['t1'], category: 'demo' },
    { id: 't3', name: 'Foundation Work', duration: 5, dependencies: ['t2'], category: 'foundation' },
    { id: 't4', name: 'Rough Framing', duration: 7, dependencies: ['t3'], category: 'framing' },
    { id: 't5', name: 'Electrical Rough-In', duration: 4, dependencies: ['t4'], category: 'electrical' },
    { id: 't6', name: 'Plumbing Rough-In', duration: 4, dependencies: ['t4'], category: 'plumbing' },
    { id: 't7', name: 'HVAC Installation', duration: 3, dependencies: ['t4'], category: 'hvac' },
    { id: 't8', name: 'Insulation', duration: 2, dependencies: ['t5', 't6', 't7'], category: 'insulation' },
    { id: 't9', name: 'Drywall Installation', duration: 4, dependencies: ['t8'], category: 'drywall' },
    { id: 't10', name: 'Interior Painting', duration: 3, dependencies: ['t9'], category: 'finish' },
    { id: 't11', name: 'Flooring Installation', duration: 3, dependencies: ['t9'], category: 'finish' },
    { id: 't12', name: 'Fixture Installation', duration: 2, dependencies: ['t10', 't11'], category: 'finish' },
    { id: 't13', name: 'Final Inspection', duration: 1, dependencies: ['t12'], category: 'finish' },
  ],
  criticalPath: [],
  totalDuration: 0,
  createdAt: Date.now(),
  createdBy: 'system',
  updatedAt: Date.now(),
};

/**
 * Task category color mapping (dark theme compatible)
 */
const CATEGORY_COLORS: Record<string, { bg: string; border: string; text: string }> = {
  prep: { bg: 'bg-slate-700/50', border: 'border-slate-500', text: 'text-slate-200' },
  demo: { bg: 'bg-red-900/50', border: 'border-red-600', text: 'text-red-300' },
  foundation: { bg: 'bg-amber-900/50', border: 'border-amber-600', text: 'text-amber-300' },
  framing: { bg: 'bg-yellow-900/50', border: 'border-yellow-600', text: 'text-yellow-300' },
  electrical: { bg: 'bg-blue-900/50', border: 'border-blue-500', text: 'text-blue-300' },
  plumbing: { bg: 'bg-cyan-900/50', border: 'border-cyan-500', text: 'text-cyan-300' },
  hvac: { bg: 'bg-green-900/50', border: 'border-green-500', text: 'text-green-300' },
  insulation: { bg: 'bg-purple-900/50', border: 'border-purple-500', text: 'text-purple-300' },
  drywall: { bg: 'bg-indigo-900/50', border: 'border-indigo-500', text: 'text-indigo-300' },
  finish: { bg: 'bg-pink-900/50', border: 'border-pink-500', text: 'text-pink-300' },
};

export function TimeView({ projectId, userId = 'system' }: TimeViewProps) {
  const [cpm, setCpm] = useState<CPM | null>(null);
  const [editableTasks, setEditableTasks] = useState<CPMTask[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [viewMode, setViewMode] = useState<ViewMode>('gantt');
  const [isDirty, setIsDirty] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const saveTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // Load CPM data from Firestore (generated by estimation pipeline)
  useEffect(() => {
    const loadCPM = async () => {
      setLoading(true);
      setError(null);

      try {
        const data = await getCPM(projectId);

        if (data && data.tasks && data.tasks.length > 0) {
          setCpm(data);
          setEditableTasks(data.tasks);
        } else {
          // No timeline data - user needs to generate an estimate first
          setCpm(null);
          setEditableTasks([]);
        }
      } catch (err) {
        console.error('Error loading CPM:', err);
        setError('Failed to load timeline data');
        setCpm(null);
        setEditableTasks([]);
      } finally {
        setLoading(false);
      }
    };

    loadCPM();
  }, [projectId]);

  // Handle task update - deferred to prevent UI freeze
  const handleUpdateTask = useCallback((taskId: string, updates: Partial<CPMTask>) => {
    // Use setTimeout to defer state update and prevent UI blocking
    setTimeout(() => {
      setEditableTasks(prevTasks => {
        const newTasks = prevTasks.map(task =>
          task.id === taskId ? { ...task, ...updates } : task
        );
        return newTasks;
      });
      setIsDirty(true);
    }, 0);
  }, []);

  // Debounced auto-save (skipped for test/dev routes without real auth)
  useEffect(() => {
    if (!isDirty) return;

    // Skip saving for test projects (dev mode)
    const isDevMode = projectId === 'test-project' || userId === 'test-user';

    // Clear existing timeout
    if (saveTimeoutRef.current) {
      clearTimeout(saveTimeoutRef.current);
    }

    // In dev mode, just mark as saved without hitting Firestore
    if (isDevMode) {
      setIsDirty(false);
      return;
    }

    // Set new timeout for debounced save to Firestore
    saveTimeoutRef.current = setTimeout(async () => {
      setIsSaving(true);
      try {
        const { criticalPath, totalDuration } = calculateCriticalPath(editableTasks);
        const updatedCpm: CPM = {
          ...cpm!,
          tasks: editableTasks,
          criticalPath,
          totalDuration,
          updatedAt: Date.now(),
        };
        await saveCPM(projectId, updatedCpm, userId);
        setIsDirty(false);
      } catch (err) {
        console.error('Auto-save failed:', err);
        setError('Failed to save changes. Will retry...');
      } finally {
        setIsSaving(false);
      }
    }, 1000); // 1 second debounce

    return () => {
      if (saveTimeoutRef.current) {
        clearTimeout(saveTimeoutRef.current);
      }
    };
  }, [isDirty, editableTasks, projectId, userId]);

  // Calculate critical path and task positions (uses editableTasks for real-time updates)
  const processedTasks = useMemo(() => {
    if (editableTasks.length === 0) return { tasks: [], criticalPath: [], totalDuration: 0 };

    const { criticalPath, totalDuration, taskEndDates } = calculateCriticalPath(editableTasks);

    // Calculate start dates for each task
    const taskStartDates = new Map<string, number>();
    editableTasks.forEach((task) => {
      const endDate = taskEndDates.get(task.id) || 0;
      taskStartDates.set(task.id, endDate - task.duration);
    });

    // Enhance tasks with calculated values
    // isCritical is always computed from CPM algorithm based on duration and dependencies
    const enhancedTasks: (CPMTask & { startDay: number; isCritical: boolean })[] = editableTasks.map(
      (task) => ({
        ...task,
        startDay: taskStartDates.get(task.id) || 0,
        isCritical: criticalPath.includes(task.id),
      })
    );

    return {
      tasks: enhancedTasks,
      criticalPath,
      totalDuration,
    };
  }, [editableTasks]);

  if (loading) {
    return (
      <div className="flex h-full items-center justify-center p-8">
        <div className="text-center">
          <div className="w-12 h-12 border-4 border-truecost-cyan border-t-transparent rounded-full animate-spin mx-auto mb-4" />
          <p className="text-truecost-text-secondary">Loading project schedule...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex h-full items-center justify-center p-8">
        <div className="text-center">
          <p className="text-truecost-danger mb-4">{error}</p>
          <button
            onClick={() => window.location.reload()}
            className="px-4 py-2 bg-truecost-cyan text-truecost-bg-primary rounded hover:bg-truecost-teal"
          >
            Retry
          </button>
        </div>
      </div>
    );
  }

  if (!cpm) {
    return (
      <div className="flex h-full items-center justify-center p-8">
        <div className="text-center max-w-md">
          {/* Calendar icon */}
          <svg
            className="w-16 h-16 mx-auto mb-4 text-truecost-text-muted"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={1.5}
              d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"
            />
          </svg>
          <h3 className="text-lg font-semibold text-truecost-text-primary mb-2">No Timeline Data</h3>
          <p className="text-truecost-text-secondary mb-4">
            Generate an estimate to see the project timeline. The timeline will be automatically created based on your project scope and requirements.
          </p>
          <p className="text-sm text-truecost-text-muted">
            Go to the Summary tab and click "Generate Estimate" to get started.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="h-full flex flex-col">
      {/* Header */}
      <div className="border-b border-truecost-glass-border px-6 py-4">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold text-truecost-text-primary">Project Timeline</h1>
            <p className="text-sm text-truecost-text-secondary mt-1">
              Total Duration: <span className="font-semibold text-truecost-cyan">{processedTasks.totalDuration} days</span>
              {processedTasks.criticalPath.length > 0 && (
                <span className="ml-4">
                  Critical Path:{' '}
                  <span className="font-semibold text-truecost-danger">
                    {processedTasks.criticalPath.length} tasks
                  </span>
                </span>
              )}
              {/* Save status indicator */}
              <span className="ml-4">
                {isSaving ? (
                  <span className="text-blue-600">
                    <svg className="inline w-4 h-4 animate-spin mr-1" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                    </svg>
                    Saving...
                  </span>
                ) : isDirty ? (
                  <span className="text-amber-600">Unsaved changes</span>
                ) : null}
              </span>
            </p>
          </div>

          {/* View Toggle */}
          <div className="flex items-center gap-1 rounded-lg border border-truecost-glass-border bg-truecost-glass-bg p-1">
            <button
              onClick={() => setViewMode('gantt')}
              className={`px-4 py-2 text-sm font-medium rounded-lg transition-all ${
                viewMode === 'gantt'
                  ? 'bg-gradient-to-r from-truecost-cyan/20 to-truecost-teal/20 border border-truecost-cyan/40 text-truecost-cyan'
                  : 'text-truecost-text-secondary hover:text-truecost-text-primary hover:bg-truecost-glass-bg border border-transparent'
              }`}
            >
              Gantt Chart
            </button>
            <button
              onClick={() => setViewMode('network')}
              className={`px-4 py-2 text-sm font-medium rounded-lg transition-all ${
                viewMode === 'network'
                  ? 'bg-gradient-to-r from-truecost-cyan/20 to-truecost-teal/20 border border-truecost-cyan/40 text-truecost-cyan'
                  : 'text-truecost-text-secondary hover:text-truecost-text-primary hover:bg-truecost-glass-bg border border-transparent'
              }`}
            >
              CPM Network
            </button>
            <button
              onClick={() => setViewMode('list')}
              className={`px-4 py-2 text-sm font-medium rounded-lg transition-all ${
                viewMode === 'list'
                  ? 'bg-gradient-to-r from-truecost-cyan/20 to-truecost-teal/20 border border-truecost-cyan/40 text-truecost-cyan'
                  : 'text-truecost-text-secondary hover:text-truecost-text-primary hover:bg-truecost-glass-bg border border-transparent'
              }`}
            >
              Task List
            </button>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-auto p-6">
        {viewMode === 'gantt' && (
          <GanttChart
            tasks={processedTasks.tasks}
            totalDuration={processedTasks.totalDuration}
          />
        )}

        {viewMode === 'network' && (
          <CPMNetworkDiagram
            tasks={processedTasks.tasks}
            criticalPath={processedTasks.criticalPath}
          />
        )}

        {viewMode === 'list' && (
          <TaskListView
            tasks={processedTasks.tasks}
            onUpdateTask={handleUpdateTask}
          />
        )}
      </div>
    </div>
  );
}

/**
 * Gantt Chart visualization
 */
function GanttChart({
  tasks,
  totalDuration,
}: {
  tasks: (CPMTask & { startDay: number; isCritical: boolean })[];
  totalDuration: number;
}) {
  // Generate day markers
  const dayMarkers = Array.from({ length: totalDuration + 1 }, (_, i) => i);

  // Calculate pixel width per day (responsive)
  const dayWidth = 40;
  const chartWidth = (totalDuration + 1) * dayWidth;

  return (
    <div className="glass-panel rounded-lg shadow-sm border border-truecost-glass-border overflow-hidden">
      {/* Legend */}
      <div className="px-4 py-2 bg-truecost-bg-secondary border-b border-truecost-glass-border flex items-center gap-4 text-sm">
        <span className="font-medium text-gray-700">Legend:</span>
        <div className="flex items-center gap-1">
          <div className="w-4 h-4 bg-red-500 rounded" />
          <span className="text-truecost-text-secondary">Critical Path</span>
        </div>
        <div className="flex items-center gap-1">
          <div className="w-4 h-4 bg-blue-500 rounded" />
          <span className="text-truecost-text-secondary">Standard Task</span>
        </div>
      </div>

      <div className="overflow-x-auto">
        <div style={{ minWidth: chartWidth + 200 }}>
          {/* Header row with "Day" label */}
          <div className="flex border-b border-truecost-glass-border">
            <div className="w-48 flex-shrink-0 px-4 py-1 bg-truecost-bg-secondary border-r border-truecost-glass-border" />
            <div className="flex-1 text-center text-xs font-medium text-truecost-text-secondary py-1 bg-truecost-bg-secondary">
              Day
            </div>
          </div>
          {/* Header row with day numbers */}
          <div className="flex border-b border-truecost-glass-border">
            <div className="w-48 flex-shrink-0 px-4 py-2 bg-truecost-bg-secondary font-medium text-truecost-text-secondary border-r border-truecost-glass-border">
              Task
            </div>
            <div className="flex-1 flex">
              {dayMarkers.map((day) => (
                <div
                  key={day}
                  className="text-center text-xs text-truecost-text-muted border-r border-truecost-glass-border py-1"
                  style={{ width: dayWidth }}
                >
                  {day + 1}
                </div>
              ))}
            </div>
          </div>

          {/* Task rows */}
          {tasks.map((task, index) => {
            return (
              <div
                key={task.id}
                className={`flex border-b border-truecost-glass-border ${
                  index % 2 === 0 ? 'glass-panel' : 'bg-truecost-bg-secondary/50'
                }`}
              >
                {/* Task name */}
                <div className="w-48 flex-shrink-0 px-4 py-3 border-r border-truecost-glass-border">
                  <div className="font-medium text-truecost-text-primary text-sm">{task.name}</div>
                  <div className="text-xs text-truecost-text-muted">
                    {task.duration} day{task.duration !== 1 ? 's' : ''}
                  </div>
                </div>

                {/* Gantt bar area */}
                <div className="flex-1 relative py-2">
                  <div
                    className={`absolute h-8 rounded cursor-pointer ${
                      task.isCritical ? 'bg-red-500' : 'bg-blue-200'
                    } ${task.isCritical ? '' : 'border-blue-400'} border flex items-center justify-center text-xs font-medium ${
                      task.isCritical ? 'text-white' : 'text-blue-800'
                    }`}
                    style={{
                      left: task.startDay * dayWidth,
                      width: task.duration * dayWidth - 4,
                      top: '50%',
                      transform: 'translateY(-50%)',
                    }}
                    title={`${task.name} (${task.duration} day${task.duration !== 1 ? 's' : ''})`}
                  >
                    {task.duration > 2 && task.name}
                    {task.isCritical && <span className="ml-1">★</span>}
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}

/**
 * Task List view with editable duration, dependencies, and critical toggle
 */
function TaskListView({
  tasks,
  onUpdateTask,
}: {
  tasks: (CPMTask & { startDay: number; isCritical: boolean })[];
  onUpdateTask?: (taskId: string, updates: Partial<CPMTask>) => void;
}) {
  const [editingDurationId, setEditingDurationId] = useState<string | null>(null);
  const [editingDepsId, setEditingDepsId] = useState<string | null>(null);
  const [durationValue, setDurationValue] = useState<string>('');
  // Local state for dependency editing (batched updates)
  const [localDeps, setLocalDeps] = useState<string[]>([]);

  // Duration editing handlers
  const handleStartDurationEdit = (task: CPMTask) => {
    // Close deps editor first and save if open
    if (editingDepsId) {
      handleSaveDeps();
    }
    setEditingDurationId(task.id);
    setDurationValue(task.duration.toString());
  };

  const handleSaveDuration = (taskId: string) => {
    const newDuration = parseInt(durationValue, 10);
    if (!isNaN(newDuration) && newDuration >= 1 && onUpdateTask) {
      onUpdateTask(taskId, { duration: newDuration });
    }
    setEditingDurationId(null);
    setDurationValue('');
  };

  const handleDurationKeyDown = (e: React.KeyboardEvent, taskId: string) => {
    if (e.key === 'Enter') {
      handleSaveDuration(taskId);
    } else if (e.key === 'Escape') {
      setEditingDurationId(null);
      setDurationValue('');
    }
  };

  // Dependencies editing handlers - uses local state, saves on close
  const handleStartDepsEdit = (task: CPMTask & { startDay: number; isCritical: boolean }) => {
    // Close duration editor if open
    if (editingDurationId) {
      setEditingDurationId(null);
      setDurationValue('');
    }
    setEditingDepsId(task.id);
    setLocalDeps([...task.dependencies]); // Copy current deps to local state
  };

  // Check if adding depId as dependency of taskId would create a cycle
  // Uses BFS to traverse from depId following dependencies to see if we can reach taskId
  const wouldCreateCycle = (taskId: string, depId: string, proposedDeps: string[]): boolean => {
    // Build a dependency map with the proposed change applied
    const depsMap = new Map<string, string[]>();
    tasks.forEach(t => {
      if (t.id === taskId) {
        // Use proposed deps for the task being edited
        depsMap.set(t.id, proposedDeps);
      } else {
        depsMap.set(t.id, t.dependencies);
      }
    });

    // BFS from depId to see if we can reach taskId
    const visited = new Set<string>();
    const queue = [depId];

    while (queue.length > 0) {
      const current = queue.shift()!;
      if (current === taskId) {
        return true; // Found a path back to taskId - cycle detected
      }
      if (visited.has(current)) {
        continue;
      }
      visited.add(current);

      const currentDeps = depsMap.get(current) || [];
      for (const dep of currentDeps) {
        if (!visited.has(dep)) {
          queue.push(dep);
        }
      }
    }

    return false;
  };

  const handleToggleDependency = (depId: string) => {
    // Only update local state - don't trigger parent update yet
    setLocalDeps(prev => {
      if (prev.includes(depId)) {
        // Removing dependency - always allowed
        return prev.filter(d => d !== depId);
      } else {
        // Adding dependency - check for cycles first
        const proposedDeps = [...prev, depId];
        if (editingDepsId && wouldCreateCycle(editingDepsId, depId, proposedDeps)) {
          console.warn(`Cannot add dependency: ${depId} -> ${editingDepsId} would create a cycle`);
          return prev; // Don't add the dependency
        }
        return proposedDeps;
      }
    });
  };

  const handleSaveDeps = () => {
    if (editingDepsId && onUpdateTask) {
      const originalTask = tasks.find(t => t.id === editingDepsId);
      // Only save if dependencies actually changed
      if (originalTask && JSON.stringify(originalTask.dependencies.sort()) !== JSON.stringify(localDeps.sort())) {
        onUpdateTask(editingDepsId, { dependencies: localDeps });
      }
    }
    setEditingDepsId(null);
    setLocalDeps([]);
  };

  const handleCancelDeps = () => {
    setEditingDepsId(null);
    setLocalDeps([]);
  };


  return (
    <div className="glass-panel rounded-lg shadow-sm border border-truecost-glass-border">
      {/* Edit hint */}
      <div className="px-4 py-2 bg-truecost-cyan/10 border-b border-truecost-glass-border text-sm text-truecost-cyan">
        Click on Duration or Dependencies to edit. Critical path updates automatically via CPM algorithm.
      </div>
      <table className="w-full">
        <thead>
          <tr className="bg-truecost-bg-secondary border-b border-truecost-glass-border">
            <th className="text-left py-3 px-4 font-semibold text-truecost-text-secondary">Task</th>
            <th className="text-left py-3 px-4 font-semibold text-truecost-text-secondary">Category</th>
            <th className="text-right py-3 px-4 font-semibold text-truecost-text-secondary">
              Duration
              <span className="ml-1 text-xs font-normal text-truecost-cyan">(edit)</span>
            </th>
            <th className="text-right py-3 px-4 font-semibold text-truecost-text-secondary">Start</th>
            <th className="text-right py-3 px-4 font-semibold text-truecost-text-secondary">End</th>
            <th className="text-center py-3 px-4 font-semibold text-truecost-text-secondary">
              Dependencies
              <span className="ml-1 text-xs font-normal text-truecost-cyan">(edit)</span>
            </th>
            <th className="text-center py-3 px-4 font-semibold text-truecost-text-secondary">
              Critical
              <span className="ml-1 text-xs font-normal text-truecost-text-muted">(auto)</span>
            </th>
          </tr>
        </thead>
        <tbody>
          {tasks.map((task, index) => (
            <tr
              key={task.id}
              className={`border-b border-truecost-glass-border ${
                task.isCritical ? 'bg-red-50' : index % 2 === 0 ? 'glass-panel' : 'bg-truecost-bg-secondary/50'
              }`}
            >
              <td className="py-3 px-4 font-medium text-truecost-text-primary">{task.name}</td>
              <td className="py-3 px-4">
                <span
                  className={`px-2 py-1 rounded text-xs font-medium ${
                    CATEGORY_COLORS[task.category || 'prep']?.bg || 'bg-gray-200'
                  } ${CATEGORY_COLORS[task.category || 'prep']?.text || 'text-gray-800'}`}
                >
                  {task.category || 'General'}
                </span>
              </td>

              {/* Editable Duration Cell */}
              <td className="py-3 px-4 text-right">
                {editingDurationId === task.id ? (
                  <div className="flex items-center justify-end gap-2">
                    <input
                      type="number"
                      min="1"
                      max="365"
                      value={durationValue}
                      onChange={(e) => setDurationValue(e.target.value)}
                      onKeyDown={(e) => handleDurationKeyDown(e, task.id)}
                      onBlur={() => handleSaveDuration(task.id)}
                      autoFocus
                      className="w-16 px-2 py-1 text-right text-truecost-text-primary bg-truecost-bg-secondary border border-truecost-cyan rounded focus:ring-2 focus:ring-truecost-cyan focus:outline-none"
                    />
                    <span className="text-truecost-text-muted text-sm">days</span>
                  </div>
                ) : (
                  <button
                    onClick={() => handleStartDurationEdit(task)}
                    className="group px-2 py-1 rounded hover:bg-truecost-cyan/20 transition-colors cursor-pointer text-truecost-text-primary"
                    title="Click to edit duration"
                  >
                    {task.duration} day{task.duration !== 1 ? 's' : ''}
                    <svg
                      className="inline-block w-3 h-3 ml-1 opacity-0 group-hover:opacity-100 text-truecost-cyan transition-opacity"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                    </svg>
                  </button>
                )}
              </td>

              <td className="py-3 px-4 text-right text-truecost-text-primary">Day {task.startDay + 1}</td>
              <td className="py-3 px-4 text-right text-truecost-text-primary">Day {task.startDay + task.duration}</td>

              {/* Editable Dependencies Cell */}
              <td className="py-3 px-4 text-center relative">
                {editingDepsId === task.id ? (
                  <div className="absolute z-10 right-0 top-full mt-1 w-64 bg-truecost-bg-secondary border border-truecost-glass-border rounded-lg shadow-lg p-2">
                    <div className="flex justify-between items-center mb-2 pb-2 border-b border-truecost-glass-border">
                      <span className="text-sm font-medium text-truecost-text-primary">Select Dependencies</span>
                      <button
                        onClick={handleCancelDeps}
                        className="text-truecost-text-muted hover:text-truecost-text-secondary"
                        title="Cancel"
                      >
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                        </svg>
                      </button>
                    </div>
                    <div className="max-h-48 overflow-y-auto space-y-1">
                      {tasks.filter(t => t.id !== task.id).map(otherTask => (
                        <label
                          key={otherTask.id}
                          className="flex items-center gap-2 p-1.5 rounded hover:bg-truecost-glass-bg cursor-pointer"
                        >
                          <input
                            type="checkbox"
                            checked={localDeps.includes(otherTask.id)}
                            onChange={() => handleToggleDependency(otherTask.id)}
                            className="rounded border-truecost-glass-border text-truecost-cyan focus:ring-truecost-cyan"
                          />
                          <span className="text-sm text-truecost-text-secondary truncate">{otherTask.name}</span>
                        </label>
                      ))}
                    </div>
                    {/* Save/Cancel buttons */}
                    <div className="flex justify-end gap-2 mt-2 pt-2 border-t border-truecost-glass-border">
                      <button
                        onClick={handleCancelDeps}
                        className="px-2 py-1 text-xs text-truecost-text-secondary hover:bg-truecost-glass-bg rounded"
                      >
                        Cancel
                      </button>
                      <button
                        onClick={handleSaveDeps}
                        className="px-2 py-1 text-xs bg-truecost-cyan text-truecost-bg-primary hover:bg-truecost-teal rounded"
                      >
                        Save
                      </button>
                    </div>
                  </div>
                ) : null}
                <button
                  onClick={() => handleStartDepsEdit(task)}
                  className="group px-2 py-1 rounded hover:bg-truecost-cyan/20 transition-colors cursor-pointer text-truecost-text-secondary text-sm"
                  title="Click to edit dependencies"
                >
                  {task.dependencies.length > 0 ? (
                    <span className="flex items-center justify-center gap-1">
                      <span className="max-w-32 truncate">
                        {tasks.filter(t => task.dependencies.includes(t.id)).map(t => t.name).join(', ')}
                      </span>
                      <span className="text-truecost-cyan text-xs">({task.dependencies.length})</span>
                    </span>
                  ) : (
                    <span className="text-truecost-text-muted">None</span>
                  )}
                  <svg
                    className="inline-block w-3 h-3 ml-1 opacity-0 group-hover:opacity-100 text-truecost-cyan transition-opacity"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                  </svg>
                </button>
              </td>

              {/* Critical Cell - Auto-calculated via CPM */}
              <td className="py-3 px-4 text-center">
                <span
                  className={`px-3 py-1 rounded-full text-sm font-medium ${
                    task.isCritical
                      ? 'bg-red-900/50 text-red-300'
                      : 'bg-truecost-glass-bg text-truecost-text-muted'
                  }`}
                  title="Automatically calculated from duration and dependencies"
                >
                  {task.isCritical ? '★ Critical' : 'Normal'}
                </span>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

/**
 * CPM Network Diagram - displays task nodes with edges showing dependencies
 * Critical path is highlighted in red
 */
function CPMNetworkDiagram({
  tasks,
  criticalPath,
}: {
  tasks: (CPMTask & { startDay: number; isCritical: boolean })[];
  criticalPath: string[];
}) {
  const [selectedTask, setSelectedTask] = useState<(CPMTask & { startDay: number; isCritical: boolean }) | null>(null);

  // Calculate node positions using a layered approach
  // Tasks are positioned based on their dependencies (topological layers)
  const nodePositions = useMemo(() => {
    const positions = new Map<string, NodePosition>();
    const NODE_WIDTH = 180;
    const NODE_HEIGHT = 100;
    const H_SPACING = 80;
    const V_SPACING = 40;

    // Build dependency graph
    const taskMap = new Map(tasks.map((t) => [t.id, t]));
    const dependents = new Map<string, string[]>();
    tasks.forEach((task) => {
      task.dependencies.forEach((depId) => {
        if (!dependents.has(depId)) {
          dependents.set(depId, []);
        }
        dependents.get(depId)!.push(task.id);
      });
    });

    // Calculate layer for each task (longest path from any start node)
    const layers = new Map<string, number>();

    function calculateLayer(taskId: string, visited: Set<string>): number {
      if (layers.has(taskId)) return layers.get(taskId)!;
      if (visited.has(taskId)) return 0; // Cycle detection

      visited.add(taskId);
      const task = taskMap.get(taskId);
      if (!task || task.dependencies.length === 0) {
        layers.set(taskId, 0);
        return 0;
      }

      let maxDepLayer = -1;
      task.dependencies.forEach((depId) => {
        maxDepLayer = Math.max(maxDepLayer, calculateLayer(depId, visited));
      });

      const layer = maxDepLayer + 1;
      layers.set(taskId, layer);
      return layer;
    }

    tasks.forEach((task) => calculateLayer(task.id, new Set()));

    // Group tasks by layer
    const layerGroups = new Map<number, string[]>();
    layers.forEach((layer, taskId) => {
      if (!layerGroups.has(layer)) {
        layerGroups.set(layer, []);
      }
      layerGroups.get(layer)!.push(taskId);
    });

    // Position nodes
    const maxLayer = Math.max(...Array.from(layers.values()));
    layerGroups.forEach((taskIds, layer) => {
      const x = layer * (NODE_WIDTH + H_SPACING) + 50;
      taskIds.forEach((taskId, index) => {
        const y = index * (NODE_HEIGHT + V_SPACING) + 50;
        positions.set(taskId, { x, y, width: NODE_WIDTH, height: NODE_HEIGHT });
      });
    });

    return { positions, maxLayer, layerGroups };
  }, [tasks]);

  // Calculate SVG dimensions
  const svgWidth = (nodePositions.maxLayer + 1) * 260 + 100;
  const maxNodesInLayer = Math.max(
    ...Array.from(nodePositions.layerGroups.values()).map((g) => g.length)
  );
  const svgHeight = maxNodesInLayer * 140 + 100;

  // Helper to calculate edge path between two nodes
  function getEdgePath(fromId: string, toId: string): string {
    const from = nodePositions.positions.get(fromId);
    const to = nodePositions.positions.get(toId);
    if (!from || !to) return '';

    const startX = from.x + from.width;
    const startY = from.y + from.height / 2;
    const endX = to.x;
    const endY = to.y + to.height / 2;

    // Bezier curve for smooth edges
    const ctrlX1 = startX + 40;
    const ctrlX2 = endX - 40;

    return `M ${startX} ${startY} C ${ctrlX1} ${startY}, ${ctrlX2} ${endY}, ${endX} ${endY}`;
  }

  // Check if edge is on critical path
  function isEdgeCritical(fromId: string, toId: string): boolean {
    const fromIndex = criticalPath.indexOf(fromId);
    const toIndex = criticalPath.indexOf(toId);
    return fromIndex !== -1 && toIndex !== -1 && toIndex === fromIndex + 1;
  }

  return (
    <div className="glass-panel rounded-lg shadow-sm border border-truecost-glass-border overflow-hidden">
      {/* Legend */}
      <div className="px-4 py-2 bg-truecost-bg-secondary border-b border-truecost-glass-border flex items-center gap-4 text-sm">
        <span className="font-medium text-gray-700">Legend:</span>
        <div className="flex items-center gap-1">
          <div className="w-4 h-4 bg-red-500 rounded border-2 border-red-700" />
          <span className="text-truecost-text-secondary">Critical Path</span>
        </div>
        <div className="flex items-center gap-1">
          <div className="w-4 h-4 bg-blue-100 rounded border-2 border-blue-400" />
          <span className="text-truecost-text-secondary">Standard Task</span>
        </div>
        <div className="flex items-center gap-1">
          <svg width="30" height="10">
            <line x1="0" y1="5" x2="30" y2="5" stroke="#ef4444" strokeWidth="3" markerEnd="url(#arrowhead-critical)" />
          </svg>
          <span className="text-truecost-text-secondary">Critical Dependency</span>
        </div>
        <div className="flex items-center gap-1">
          <svg width="30" height="10">
            <line x1="0" y1="5" x2="30" y2="5" stroke="#9ca3af" strokeWidth="2" />
          </svg>
          <span className="text-truecost-text-secondary">Standard Dependency</span>
        </div>
      </div>

      {/* Network Diagram */}
      <div className="overflow-auto p-4" style={{ maxHeight: '70vh' }}>
        <svg width={svgWidth} height={svgHeight} className="min-w-full">
          <defs>
            {/* Arrowhead marker for critical edges */}
            <marker
              id="arrowhead-critical"
              markerWidth="10"
              markerHeight="7"
              refX="9"
              refY="3.5"
              orient="auto"
            >
              <polygon points="0 0, 10 3.5, 0 7" fill="#ef4444" />
            </marker>
            {/* Arrowhead marker for standard edges */}
            <marker
              id="arrowhead-standard"
              markerWidth="10"
              markerHeight="7"
              refX="9"
              refY="3.5"
              orient="auto"
            >
              <polygon points="0 0, 10 3.5, 0 7" fill="#9ca3af" />
            </marker>
          </defs>

          {/* Draw edges first (so they appear behind nodes) */}
          {tasks.map((task) =>
            task.dependencies.map((depId) => {
              const isCritical = isEdgeCritical(depId, task.id);
              return (
                <path
                  key={`${depId}-${task.id}`}
                  d={getEdgePath(depId, task.id)}
                  fill="none"
                  stroke={isCritical ? '#ef4444' : '#9ca3af'}
                  strokeWidth={isCritical ? 3 : 2}
                  markerEnd={isCritical ? 'url(#arrowhead-critical)' : 'url(#arrowhead-standard)'}
                  className="transition-all"
                />
              );
            })
          )}

          {/* Draw nodes */}
          {tasks.map((task) => {
            const pos = nodePositions.positions.get(task.id);
            if (!pos) return null;

            const ES = task.startDay; // Early Start
            const EF = task.startDay + task.duration; // Early Finish
            // For simplicity, LS/LF = ES/EF for critical tasks, otherwise calculate slack
            const slack = task.isCritical ? 0 : 1; // Simplified - in real CPM this would be calculated
            const LS = ES + slack; // Late Start
            const LF = EF + slack; // Late Finish

            return (
              <g
                key={task.id}
                transform={`translate(${pos.x}, ${pos.y})`}
                onClick={() => setSelectedTask(task)}
                className="cursor-pointer"
              >
                {/* Node background */}
                <rect
                  width={pos.width}
                  height={pos.height}
                  rx="8"
                  ry="8"
                  fill={task.isCritical ? '#fef2f2' : '#f0f9ff'}
                  stroke={task.isCritical ? '#ef4444' : '#3b82f6'}
                  strokeWidth={task.isCritical ? 3 : 2}
                  className="transition-all hover:stroke-[4px]"
                />

                {/* Task name header */}
                <rect
                  width={pos.width}
                  height={28}
                  rx="8"
                  ry="8"
                  fill={task.isCritical ? '#ef4444' : '#3b82f6'}
                />
                <rect
                  y={20}
                  width={pos.width}
                  height={8}
                  fill={task.isCritical ? '#ef4444' : '#3b82f6'}
                />

                {/* Task name */}
                <text
                  x={pos.width / 2}
                  y={18}
                  textAnchor="middle"
                  className="text-xs font-semibold"
                  fill="white"
                >
                  {task.name.length > 20 ? task.name.substring(0, 18) + '...' : task.name}
                </text>

                {/* Duration */}
                <text x={pos.width / 2} y={45} textAnchor="middle" className="text-xs fill-gray-600">
                  Duration: {task.duration} day{task.duration !== 1 ? 's' : ''}
                </text>

                {/* ES/EF row */}
                <text x={10} y={65} className="text-[10px] fill-gray-500">
                  ES: {ES}
                </text>
                <text x={pos.width - 10} y={65} textAnchor="end" className="text-[10px] fill-gray-500">
                  EF: {EF}
                </text>

                {/* LS/LF row */}
                <text x={10} y={82} className="text-[10px] fill-gray-500">
                  LS: {LS}
                </text>
                <text x={pos.width - 10} y={82} textAnchor="end" className="text-[10px] fill-gray-500">
                  LF: {LF}
                </text>

                {/* Float/Slack */}
                <text x={pos.width / 2} y={95} textAnchor="middle" className="text-[10px] fill-gray-400">
                  Float: {slack}
                </text>

                {/* Critical path indicator */}
                {task.isCritical && (
                  <text
                    x={pos.width - 8}
                    y={18}
                    textAnchor="end"
                    className="text-xs fill-yellow-300 font-bold"
                  >
                    ★
                  </text>
                )}
              </g>
            );
          })}
        </svg>
      </div>

      {/* Task Detail Modal */}
      {selectedTask && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50" onClick={() => setSelectedTask(null)}>
          <div className="glass-panel rounded-lg shadow-xl p-6 max-w-md w-full mx-4" onClick={(e) => e.stopPropagation()}>
            <div className="flex justify-between items-start mb-4">
              <h3 className="text-lg font-bold text-truecost-text-primary">{selectedTask.name}</h3>
              <button
                onClick={() => setSelectedTask(null)}
                className="text-truecost-text-muted hover:text-truecost-text-secondary"
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>

            <div className="space-y-3">
              <div className="flex justify-between">
                <span className="text-truecost-text-secondary">Category:</span>
                <span className={`px-2 py-1 rounded text-xs font-medium ${CATEGORY_COLORS[selectedTask.category || 'prep']?.bg || 'bg-gray-200'} ${CATEGORY_COLORS[selectedTask.category || 'prep']?.text || 'text-gray-800'}`}>
                  {selectedTask.category || 'General'}
                </span>
              </div>
              <div className="flex justify-between">
                <span className="text-truecost-text-secondary">Duration:</span>
                <span className="font-medium">{selectedTask.duration} day{selectedTask.duration !== 1 ? 's' : ''}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-truecost-text-secondary">Start Day:</span>
                <span className="font-medium">Day {selectedTask.startDay + 1}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-truecost-text-secondary">End Day:</span>
                <span className="font-medium">Day {selectedTask.startDay + selectedTask.duration}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-truecost-text-secondary">Critical Path:</span>
                {selectedTask.isCritical ? (
                  <span className="text-red-600 font-bold">★ Yes</span>
                ) : (
                  <span className="text-truecost-text-muted">No</span>
                )}
              </div>
              {selectedTask.dependencies.length > 0 && (
                <div>
                  <span className="text-truecost-text-secondary">Dependencies:</span>
                  <div className="mt-1 flex flex-wrap gap-1">
                    {selectedTask.dependencies.map((depId) => {
                      const depTask = tasks.find((t) => t.id === depId);
                      return (
                        <span key={depId} className="px-2 py-0.5 bg-gray-100 rounded text-xs">
                          {depTask?.name || depId}
                        </span>
                      );
                    })}
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
